config/routes.rb
Rails.application.routes.draw do

  resources :guests

  get 'aimmailers/index'

  get 'aimmailers/new'

  get 'aimmailers/edit'

  get 'aimmailers/update'

  get 'aimmailers/destroy'

  get 'aimmailers/delete'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  post 'signup' => 'users#create'

  resources :users

  get '/members/executives' => 'members#executives'

  resources :members

  resources :news
 
	get 'pages/home' #refers to the controller Pages and the method within it 'home'
  get 'pages/sponsorship'
  get 'pages/calendar'
  get 'pages/recess'
  root 'pages#home' #makes the home page our default webpage

end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  before_action :require_user, only: [:show, :edit, :index]
  before_action :require_admin, only: [:delete, :destroy]
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        #Send the new_member_email after saving
        #if @guest.type == 'corporate'
          #GuestMailer.corporate_email(@guest).deliver_later
        #elsif @guest.type == 'member'
          #GuestMailer.new_member_email(@guest).deliver_later
        #end
        format.html { redirect_to '/', notice: 'We got your message! You will hear from us soon!' }
      else
        format.html { render :new, alert: 'There was an error, fill out the form carefully and try again' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:first_name, :last_name, :email, :phone_number, :company, :subject, :message, :major, :grad_season, :grad_year, :type)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<div class="forms">
	<%= form_for(@guest) do |f| %>
  	<label>First Name</label>
		<%= @guest.errors.get(:first_name).first unless @guest.errors.get(:first_name).nil? %><br>
  	<%= f.text_field :first_name %><br>
  	<label>Last Name</label>
		<%= @guest.errors.get(:last_name).first unless @guest.errors.get(:last_name).nil? %><br>
  	<%= f.text_field :last_name %><br>
  	<label>Major</label><br>
  	<%= f.select(:major, @majors, prompt: 'Select Major', class: 'major') %><br>
  	<label>Graduation Date</label><br>
  	<%= f.select(:grad_season, @grad_month, prompt: 'Month', class: 'grad_year') %>
  	<%= f.select(:grad_year, Date.today.year..Date.today.year+5, prompt: 'Year') %><br>
  	<label>E-Mail</label><br>
		<%= @guest.errors.get(:email).first unless @guest.errors.get(:email).nil? %>
  	<%= f.text_field :email, placeholder: '***@uncc.edu' %><br>
  	<label>Phone Number</label><br>
  	<%= f.telephone_field :phone_number %><br>
  	<%= f.label :message %><br>
  	<%= f.text_area :message, size: '24x5' %><br>
  	<%= f.submit 'Send Message' %>
  	<b><%= link_to 'Cancel', '/' %></b>
	<% end %>
</div>

app/views/guests/edit.html.erb
<main>
	<header>
  	<h1>
  	  Edit Mail
  	</h1>
	</header>
	<%= render 'form' %>
	<%= link_to 'Show', @guest %> |
	<%= link_to 'Back', guests_path %>
</main>

app/views/guests/index.html.erb
<main>
<header>
  <h1>Mail Database</h1>
</header>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Message</th>
      <th>Major</th>
      <th>Graduation Date</th>
      <th colspan="3">Data Options</th>
    </tr>
  </thead>
  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.first_name %></td>
        <td><%= guest.last_name %></td>
        <td><%= guest.email %></td>
        <td><%= guest.phone_number %></td>
        <td><%= guest.message %></td>
        <td><%= guest.major %></td>
        <td><%= guest.grad_season + ' ' + guest.grad_year %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</br>
</main>

app/views/guests/new.html.erb
<main>
	<header>
  	<h1>
  	  Join AIM Now!
  	</h1>
  	<h3>
  	  Send us your email address and phone number to join our mailing list and GroupMe!
  	</h3>
	</header>
	<%= render 'form' %>
</main>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @guest.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @guest.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @guest.phone_number %>
</p>

<p>
  <strong>Company:</strong>
  <%= @guest.company %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @guest.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @guest.message %>
</p>

<p>
  <strong>Major:</strong>
  <%= @guest.major %>
</p>

<p>
  <strong>Graduation Date:</strong>
  <%= @guest.grad_season + ' ' + @guest.grad_year %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= button_to 'Back', guests_path %>