config/routes.rb
Rails.application.routes.draw do

  resources :guests

  get 'aimmailers/index'

  get 'aimmailers/new'

  get 'aimmailers/edit'

  get 'aimmailers/update'

  get 'aimmailers/destroy'

  get 'aimmailers/delete'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  post 'signup' => 'users#create'

  resources :users

  get '/members/executives' => 'members#executives'

  resources :members

  resources :news
 
	get 'pages/home' #refers to the controller Pages and the method within it 'home'
  get 'pages/sponsorship'
  get 'pages/calendar'
  get 'pages/recess'
  root 'pages#home' #makes the home page our default webpage

end

app/models/news.rb
class News < ActiveRecord::Base
  has_attached_file :thumbnail, styles: {
      thumb: ['100x100#',  :jpg, :quality => 70],
      preview: ['480x480#',  :jpg, :quality => 70],
      large:['600>',      :jpg, :quality => 70]
    },
    convert_options: {
      thumb: '-set colorspace sRGB -strip',
      preview: '-set colorspace sRGB -strip',
      large: '-set colorspace sRGB -strip'
    }

  validates_attachment :thumbnail,
    size: { in: 0..10.megabytes },
    content_type: { content_type: /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  before_action :require_user, only: [:new, :show, :edit]
  before_action :require_admin, only: [:delete, :destroy]
  before_action :find_news, only: [:edit, :update, :delete, :destroy]

  def find_news
    @news = News.find(params[:id])
  end

  def index
    @news = News.all.sort_by{|news| news.date.to_date}.reverse #sorts the news entries so that the latest feeds are on top
  end

  def show #This is form filtering entries, this method won't be needed for news entries
  end

  def new
    @news = News.new #creates new News entry
  end

  def create
    @news = News.new(news_params) #the new News entry is recreated through the strong params method
      if @news.save #if the entry saves
        redirect_to({ action: 'index' }, notice: @news.title + ' has been created!') #show all of the present entries
      else
        redirect_to({ action: 'new' }, alert: 'There was an error, fill out the form carefully and try again')
      end
  end

  def edit
  end

  def update
      if @news.update_attributes(news_params)
        redirect_to({ action: 'index' }, notice: @news.title + ' has been updated!')
      else
        render(:action => 'index')
      end
  end

  def delete
  end

  def destroy
    @news.destroy
    redirect_to({ action: 'index' }, alert: 'The news post has been deleted!')
  end
  
  private
    def news_params
      params.require(:news).permit(:title, :date, :mediatype, :youtubeurl, :thumbnail, :description)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<div class="forms">
	<%= form_for(@news) do |news| %>
  	<%= news.label :title %><br>
  	<%= news.text_field :title %><br>
  	<%= news.label :date %><br>
  	<%= news.date_field :date, value: @news.date %><br>
  	<%= news.radio_button :mediatype, 'Image', id: 'image_input' %><%= news.label :mediatype, 'Image' %>
  	<%= news.radio_button :mediatype, 'Video', id: 'video_input' %><%= news.label :mediatype, 'Video' %><br/>
		<%= news.label 'Photo', id: 'image_input', class: 'news_media' %><br>
		<%= news.file_field :thumbnail, id: 'image_input', class: 'news_media' %><br>
  	<label id="video_input" class="news_media">Paste the YouTube video URL here:</label></br>
  	<%= news.text_area :youtubeurl, id: 'video_input', class: 'news_media' %><br>
  	<%= news.label :description %><br>
  	<%= news.text_area :description %><br>
  	<br><%= news.submit %>
  	<b><%= link_to "Cancel", '/news' %></b>
	<% end %>
</div>

app/views/news/delete.html.erb
<h1>News#delete</h1>
<p>Find me in app/views/news/delete.html.erb</p>
<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Thumburl:</strong>
  <%= @news.thumburl %>
</p>

app/views/news/edit.html.erb
<main>
	<header>
	  <h1>
	    Edit News
	  </h1>
	</header>
	<%= render 'form' %>
</main>

app/views/news/index.html.erb
<main>
	<header>
  	<h1>
  	  News
  	</h1>
  	<h2>
  	  See what AIM&#39;s been up to!
  	</h2>
	</header>
<% if current_user && current_user.editor? || current_user && current_user.admin? %>
  <%= button_to "Post an Update", new_news_path, :class => "button", :method => :get  %></br>
<% end %>
<div class="news_feed">
<% @news.each do |news| %>
  <section class="news">
    <figure>
      <% if news.mediatype == 'Image' %>
				<%= image_tag news.thumbnail.url(:preview), alt: news.title %>
      <% elsif news.mediatype == 'Video' %>
        <iframe src=<%= news.youtubeurl %> frameborder="0" allowfullscreen></iframe>
      <% end %>
      <figcaption>
        <p>
          <h2><%= news.title %></h2>
        </p>
        <p>
          <%= news.date.to_date.to_formatted_s(:long_ordinal) %>
        </p>
        <p>
          <%= news.description %>
        </p>
        <% if current_user && current_user.editor? || current_user && current_user.admin? %>
          <!--<%= link_to 'Show', news %> -->
          <%= link_to 'Edit', edit_news_path(news) %>
        <% end %>
          <% if current_user && current_user.admin? %>
          <%= link_to 'Delete', news, method: :delete, data: { confirm: 'Are you sure you want to delete ' + news.title + '?'}%>
        <% end %>
      </figcaption>
    </figure>
  </section>
<% end %>
</div>
</main>

app/views/news/new.html.erb
<main>
	<header>
  	<h1>
  	  Post News
  	</h1>
	</header>
	<%= render 'form' %>
	<% if flash[:notice] %>
	    <div id="notice"><%= flash[:notice] %></div>
	<% end %>
</main>

app/views/news/show.html.erb
<h1>News#show</h1>
<p>Find me in app/views/news/show.html.erb</p>