config/routes.rb
Rails.application.routes.draw do

  resources :guests

  get 'aimmailers/index'

  get 'aimmailers/new'

  get 'aimmailers/edit'

  get 'aimmailers/update'

  get 'aimmailers/destroy'

  get 'aimmailers/delete'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  post 'signup' => 'users#create'

  resources :users

  get '/members/executives' => 'members#executives'

  resources :members

  resources :news
 
	get 'pages/home' #refers to the controller Pages and the method within it 'home'
  get 'pages/sponsorship'
  get 'pages/calendar'
  get 'pages/recess'
  root 'pages#home' #makes the home page our default webpage

end

app/models/member.rb
class Member < ActiveRecord::Base

  MAJORS = ['Accounting', 'Africana Studies', 'Anthropology', 'Architecture', 'Art', 'Art History', 'Athletic Training', 'Biology', 'Business Administration', 'Chemistry', 'Child and Family Development', 'Civil Engineering', 'Civil Engineering Technology', 'Computer Science', 'Computer Engineering', 'Construction Management', 'Criminal Justice', 'Dance', 'Earth and Environmental Sciences', 'Economics', 'Electrical Engineering', 'Electrical Engineering Technology', 'Elementary Education', 'English', 'Environmental Studies', 'Exercise Science', 'Finance', 'Fire Safety Engineering Technology', 'French', 'Geography', 'Geology', 'German', 'History', 'International Business', 'International Studies', 'Japanese', 'Latin American Studies', 'Management', 'Management Information Systems', 'Marketing', 'Mathematics', 'Mathematics for Business', 'Mechanical Engineering', 'Mechanical Engineering Technology', 'Meteorology', 'Middle Grades Education', 'Music', 'Neurodiagnostics and Sleep Science', 'Nursing', 'Ops & Supply Chain Management', 'Pre-Law', 'Philosophy', 'Physics', 'Political Science', 'Psychology', 'Public Health', 'Religious Studies', 'Respiratory Therapy', 'Social Work', 'Sociology', 'Spanish', 'Special Education', 'Systems Engineering', 'Theatre']
  POSITIONS = ['President', 'Vice President', 'Treasurer', 'Secretary', 'Strategic Advisor', 'Director of Strategic Partnerships', 'Director of Programs', 'Director of Public Relations', 'Director of Publications', 'Director of Community Service', 'Director of Fundraising', 'Historian', 'Digital Administrator']
  GRAD_MONTHS = ['May', 'December']

	validates_presence_of :first_name, message: 'Please enter your first name'
	validates_presence_of :last_name, message: 'Please enter your last name'
  validates_presence_of :avatar, message: 'If you are creating a new executive, you must attach a photo', on: :create
  validates_format_of :email, with: /\A\w+@\w+\.\w+\Z/i, message: 'Please enter a valid email address'
  validates :major, inclusion: { in: MAJORS, allow_blank: false, message: 'Please enter a major' }
  validates :executive_position, inclusion: { in: POSITIONS, allow_blank: false, message: 'An executive must have a position!' }

  has_attached_file :avatar, styles: {
      thumb: ['100x100#',  :jpg, :quality => 70],
      preview: ['480x480#',  :jpg, :quality => 70],
      large:['600>',      :jpg, :quality => 70]
    },
    convert_options: {
      thumb: '-set colorspace sRGB -strip',
      preview: '-set colorspace sRGB -strip',
      large: '-set colorspace sRGB -strip'
    }

  validates_attachment :avatar,
    size: { in: 0..10.megabytes },
    content_type: { content_type: /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :find_member, only: [:edit, :update, :delete, :destroy]
  before_action :require_user, only: [:new, :show, :edit]
  before_action :require_admin, only: [:delete, :destroy]

  def find_member
    @members = Member.find(params[:id])
  end

  def index
    @members = Member.all
  end

  def show #for filtering entries
  end

  def new
    @members = Member.new
  end

  def create
    @members = Member.new(members_params) #the new Members entry is recreated through the strong params method
    @members.is_executive = true #Remove for members feature
    if @members.save #if the entry saves
      redirect_to({ action: 'executives' }, notice: @members.first_name + ' ' + @members.last_name + ' has been created!') #show all of the present entries
    else
      render({ action: 'new' }) #redisplay the create an entry page
    end
  end

  def edit
  end

  def update
    if @members.update_attributes(members_params)
      @members.is_executive = true #Remove for members feature
      redirect_to({ action: 'executives' }, notice: @members.first_name + ' ' + @members.last_name + ' has been updated!')
    else
      redirect_to({ action: 'new' }, alert: 'There was an error, fill out the form carefully and try again') #change for members
    end
  end

  def delete
  end

  def destroy
    @members.destroy
    redirect_to({ action: 'executives' }, alert: 'The member has been deleted!') #change for members
  end

  def executives
    @members = Member.where(is_executive: true).sort_by {|member| Member::POSITIONS.index(member.executive_position)}
  end

  private
    def members_params
      params.require(:member).permit(:first_name, :last_name, :linkedinurl, :major, :email, :graduation_date, :is_executive, :executive_position, :avatar)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<div class="forms">
	<%= form_for(@members) do |member| %>
		<small>* = Required</small><br>
  	<label>First Name*</label><br>
		<% if !@members.errors.get(:first_name).nil? %>
		<small><%= @members.errors.get(:first_name).first unless @members.errors.get(:first_name).nil? %></small><br>
		<% end %>
  	<%= member.text_field :first_name %><br>
  	<label>Last Name*</label><br>
		<% if !@members.errors.get(:last_name).nil? %>
		<small><%= @members.errors.get(:last_name).first %></small><br>
		<% end %>
  	<%= member.text_field :last_name %><br>
  	<label>LinkedIn Profile Address</label><br>
  	<%= member.url_field :linkedinurl %><br><br>
		<label>Photo*</label><br>
		<% if !@members.errors.get(:avatar).nil? %>
		<small><%= @members.errors.get(:avatar).first unless @members.errors.get(:avatar).nil? %></small><br>
		<% end %>
		<%= member.file_field :avatar %><br>
  	<%= member.label 'Major*' %><br>
		<% if !@members.errors.get(:major).nil? %>
		<small><%= @members.errors.get(:major).first unless @members.errors.get(:major).nil? %></small><br>
		<% end %>
  	<%= member.select(:major, Member::MAJORS, selected: @members.major, prompt: 'Select Major') %><br>
  	<label>E-Mail*</label><br>
  	<%= member.text_field :email %><br>
  	<label>Graduation Date</label><br>
  	<%= member.select(:graduation_date, Member::GRAD_MONTHS, selected: @members.graduation_date, prompt: 'Month') %>
		<%= member.select(:graduation_date, Date.today.year..Date.today.year+5, prompt: 'Year') %><br><br>
  	<!-- <%= member.label(:is_executive, "Is this member an executive?") %>
  	<%= member.check_box(:is_executive) %></br> -->
  	<label>Executive Position*</label><br>
		<% if !@members.errors.get(:executive_position).nil? %>
		<small><%= @members.errors.get(:executive_position).first unless @members.errors.get(:executive_position).nil? %></small><br>
		<% end %>
  	<%= member.select(:executive_position, Member::POSITIONS, selected: @members.executive_position, prompt: 'Select Position') %><br>
		<%= member.submit %>
		<b><%= link_to "Cancel", '/members/executives'%></b>
	<% end %>
</div>

app/views/members/delete.html.erb
<h1>Members#delete</h1>
<p>Find me in app/views/members/delete.html.erb</p>

app/views/members/edit.html.erb
<main>
	<header>
	  <h1>
	    Edit Executive <%= @members.first_name + " " %> <%= @members.last_name %>
	  </h1>
	</header>
	<%= render 'form' %>
</main>

app/views/members/executives.html.erb
<main>
	<header>
	  <h1>
	    Executive Board
	  </h1>
	  <h2>
	  AIM&#39;s team consists of highly talented and creative individuals who are passionate about improving the world through teamwork and innovation.
	  </h2>
	</header>
<% if current_user && current_user.editor? || current_user && current_user.admin? %>
  <%= button_to "New Executive", new_member_path, :class => "button", :method => :get  %></br>
<% end %>
	<div class="eboard">
<% @members.each do |member| %>
  <% full_name = member.first_name + member.last_name %>
  <section class="board_member">
    <figure>
			<%= image_tag member.avatar.url(:preview), alt: member.first_name + ' ' + member.last_name %>
      <figcaption>
        <p>
          <b><%= member.executive_position %></b>
        </p>
        <% if member.linkedinurl.include? 'http' %>
          <p>
            <script id= "linkedin" src="//platform.linkedin.com/in.js" type="text/javascript"></script>
            <script type="IN/MemberProfile" data-id="<%= member.linkedinurl %>" data-format="hover" data-text="<%= member.first_name + " " %> <%= member.last_name %>" data-related="false"></script>
          </p>
        <% else %>
          <p>
            <%= member.first_name + " " %> <%= member.last_name %>
          </p>
        <% end %>
        <p>
          <%= member.email %>
        </p>
        <p>
          <%= member.major %>
        </p>
          <% if current_user && current_user.editor? || current_user && current_user.admin? %>
            <!-- <%= link_to 'Show', member_path(member) %> -->
            <%= link_to 'Edit', edit_member_path(member) %>
          <% end %>
          <% if current_user && current_user.admin? %>
            <%= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure you want to delete ' + member.first_name + '?'}%>
          <% end %>
      </figcaption>
    </figure>
  </section>
<% end %>
	</div>
</main>

app/views/members/new.html.erb
<main>
	<header>
  	<h1>
  	  New Executive
  	</h1>
	</header>
	<%= render 'form' %>
</main>

app/views/members/show.html.erb
<h1>Members#show</h1>
<p>Find me in app/views/members/show.html.erb</p>